### ISSUE TITLE
The middleware when deny a request crash the server

### ISSUE THREAD

**Issue by mcarboni-redant** [baminteractive/express-ipfilter#37]
When the server receives a request from a blacklisted IP, the server crashes immediately.

```
Access denied to IP address: ::ffff:127.0.0.1
Error
    at /Users/mauriziocarboni/development/novus/novus-api/node_modules/express-ipfilter/src/ipfilter.js:186:15
    at Layer.handle [as handle_request] (/Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/router/index.js:312:13)
    at /Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/router/index.js:280:7
    at next (/Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/router/index.js:312:13)
    at /Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/router/index.js:280:7
    at next (/Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/router/index.js:271:10)
    at query (/Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/middleware/query.js:44:5)
    at Layer.handle [as handle_request] (/Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/router/index.js:312:13)
    at /Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/router/index.js:280:7
    at next (/Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/router/index.js:176:3)
    at Function.handle (/Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/application.js:173:10)
    at Server.app (/Users/mauriziocarboni/development/novus/novus-api/node_modules/express/lib/express.js:38:9)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:547:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

**Comment by ryanbillingsley** [comment]
@mcarboni-redant how are you handling errors that get raised from ipfilter?

**Comment by mcarboni-redant** [comment]
Hello @ryanbillingsley , I'm using the following code:

```
app.use(function(err, req, res) {
  console.error('Error handler', err)
  res.sendStatus(err.status || 500)
})
```

But seems that isn't reached

**Comment by mcarboni-redant** [comment]
@ryanbillingsley I've solved, I didn't know that express counts the number of arguments to know which functions are error handlers

**Comment by ryanbillingsley** [comment]
@mcarboni-redant great, glad you found a solution 👍

**Comment by mcarboni-redant** [comment]
Can I suggest to put in the readme a little section about error handling for Ip Filter?

From the code in the folder "examples" I've found that the package exports an error type called *IpDeniedError*.

**Comment by ryanbillingsley** [comment]
@mcarboni-redant yes, that is a good idea. thanks

**Comment by ryanbillingsley** [comment]
Added documentation
